from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "20260727_01"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contentitem',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('licence', sa.String(), nullable=False),
    sa.Column('skill_mapping', sa.JSON(), nullable=True),
    sa.Column('difficulty_estimate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentitem_domain'), 'contentitem', ['domain'], unique=False)
    op.create_table('deletionaudit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('affected_rows', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletionaudit_player_id'), 'deletionaudit', ['player_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('engine_analysis_id', sa.String(), nullable=False),
    sa.Column('claim', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('producer', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('game',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pgn', sa.String(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('moves', sa.JSON(), nullable=True),
    sa.Column('white', sa.String(), nullable=False),
    sa.Column('black', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotencyrecord',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=False),
    sa.Column('headers', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('player',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewschedule',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('player_id', 'item_id')
    )
    op.create_table('skillstate',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('concept_code', sa.String(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('prior_alpha', sa.Float(), nullable=False),
    sa.Column('prior_beta', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('player_id', 'concept_code')
    )
    op.create_table('studysession',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studysession_domain'), 'studysession', ['domain'], unique=False)
    op.create_index(op.f('ix_studysession_player_id'), 'studysession', ['player_id'], unique=False)
    op.create_table('transfermeasurement',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cohort_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('measurement_point', sa.Enum('PRE_TEST', 'IMMEDIATE_POST_TEST', 'DELAYED_TEST', name='measurementpoint'), nullable=False),
    sa.Column('source_position_id', sa.String(), nullable=False),
    sa.Column('target_position_id', sa.String(), nullable=True),
    sa.Column('source_fen', sa.String(), nullable=False),
    sa.Column('target_fen', sa.String(), nullable=False),
    sa.Column('transfer_kind', sa.Enum('NEAR', 'FAR', name='transferkind'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'player_id', 'skill_id', 'measurement_point', name='uq_transfer_measurement_cohort_player_skill_point')
    )
    op.create_index('ix_transfer_measurement_cohort_skill_point', 'transfermeasurement', ['cohort_id', 'skill_id', 'measurement_point'], unique=False)
    op.create_index('ix_transfer_measurement_player_scheduled', 'transfermeasurement', ['player_id', 'scheduled_for'], unique=False)
    op.create_table('transferposition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('opening', sa.String(), nullable=False),
    sa.Column('board_side', sa.String(), nullable=False),
    sa.Column('attacking_piece', sa.String(), nullable=False),
    sa.Column('material_count', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_position_skill_difficulty', 'transferposition', ['skill_id', 'difficulty'], unique=False)
    op.create_table('analysisjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coachstudentlink',
    sa.Column('coach_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('coach_id', 'student_id')
    )
    op.create_table('contentattempt',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('hint_assisted', sa.Boolean(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['contentitem.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['studysession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contentattempt_item_id'), 'contentattempt', ['item_id'], unique=False)
    op.create_index(op.f('ix_contentattempt_player_id'), 'contentattempt', ['player_id'], unique=False)
    op.create_index(op.f('ix_contentattempt_session_id'), 'contentattempt', ['session_id'], unique=False)
    op.create_table('persistedlessonopportunity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lesson_spec', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persistedlessonopportunity_game_id'), 'persistedlessonopportunity', ['game_id'], unique=False)
    op.create_table('playercredential',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_playercredential_token_hash'), 'playercredential', ['token_hash'], unique=False)
    op.create_table('playerprofile',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('playsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=True),
    sa.Column('opponent_config', sa.JSON(), nullable=True),
    sa.Column('clock_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=True),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('half_move_clock', sa.Integer(), nullable=False),
    sa.Column('full_move_number', sa.Integer(), nullable=False),
    sa.Column('side_to_move', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineanalysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('raw_result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engineanalysis')
    op.drop_table('position')
    op.drop_table('playsession')
    op.drop_table('playerprofile')
    op.drop_index(op.f('ix_playercredential_token_hash'), table_name='playercredential')
    op.drop_table('playercredential')
    op.drop_index(op.f('ix_persistedlessonopportunity_game_id'), table_name='persistedlessonopportunity')
    op.drop_table('persistedlessonopportunity')
    op.drop_index(op.f('ix_contentattempt_session_id'), table_name='contentattempt')
    op.drop_index(op.f('ix_contentattempt_player_id'), table_name='contentattempt')
    op.drop_index(op.f('ix_contentattempt_item_id'), table_name='contentattempt')
    op.drop_table('contentattempt')
    op.drop_table('coachstudentlink')
    op.drop_table('analysisjob')
    op.drop_index('ix_transfer_position_skill_difficulty', table_name='transferposition')
    op.drop_table('transferposition')
    op.drop_index('ix_transfer_measurement_player_scheduled', table_name='transfermeasurement')
    op.drop_index('ix_transfer_measurement_cohort_skill_point', table_name='transfermeasurement')
    op.drop_table('transfermeasurement')
    op.drop_index(op.f('ix_studysession_player_id'), table_name='studysession')
    op.drop_index(op.f('ix_studysession_domain'), table_name='studysession')
    op.drop_table('studysession')
    op.drop_table('skillstate')
    op.drop_table('reviewschedule')
    op.drop_table('player')
    op.drop_table('idempotencyrecord')
    op.drop_table('game')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_deletionaudit_player_id'), table_name='deletionaudit')
    op.drop_table('deletionaudit')
    op.drop_index(op.f('ix_contentitem_domain'), table_name='contentitem')
    op.drop_table('contentitem')
    # ### end Alembic commands ###
